spring.application.name=FastDelivery
server.port=${PORT:8000}
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/fastdelivery}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:admin}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.show-sql=${SHOW_SQL:false}
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=${SQL_INIT_MODE:always}
spring.jackson.deserialization.fail-on-unknown-properties=true
jwt.secret=${JWT_SECRET:fastdelivery-solo-desarrollo-cambiar-esta-clave-32-bytes}
jwt.expiration=${JWT_EXPIRATION:86400000}
